//  🖥️ TUIKit — Terminal UI Kit for Swift
//  ExampleStrings+Languages.swift
//
//  Created by LAYERED.work
//  License: MIT
//
//  Per-language translation tables for the example app. English is the source
//  of truth; other languages fall back to English (then the key) for any key
//  they omit. Tables grow as more pages are localized.

extension ExampleStrings {
    static let en: [String: String] = [
        "app.title": "🖥️ TUIkit Example App 💫",
        "app.subtitle": "A SwiftUI-like framework for Terminal User Interfaces 😎",
        "menu.title": "Select a Demo",
        "menu.item.textStyles": "Text Styles",
        "menu.item.colors": "Colors",
        "menu.item.containers": "Container Views",
        "menu.item.overlays": "Overlays & Modals",
        "menu.item.layout": "Layout System",
        "menu.item.buttons": "Buttons & Links",
        "menu.item.toggles": "Toggles",
        "menu.item.textFields": "Text Fields",
        "menu.item.secureFields": "Secure Fields",
        "menu.item.radioButtons": "Radio Buttons",
        "menu.item.spinners": "Spinners",
        "menu.item.lists": "Lists",
        "menu.item.tables": "Tables",
        "menu.item.scrollView": "Scroll View",
        "menu.item.sliders": "Sliders",
        "menu.item.steppers": "Steppers",
        "menu.item.splitView": "Split View",
        "menu.item.imageFile": "Image (File)",
        "menu.item.imageURL": "Image (URL)",
        "menu.item.emoji": "Emoji & SF Symbols",
        "menu.item.picker": "Picker",
        "menu.item.progress": "Progress & Gauges",
        "menu.item.mouse": "Mouse",
        "menu.item.theme": "Theme",
        "menu.item.emptyState": "Empty State",
        "menu.item.tabViews": "Tab Views",
        "menu.item.forms": "Forms",
        "status.nav": "nav",
        "status.select": "select",
        "status.back": "back",
        "status.scroll": "scroll",
        "feature.pureSwift.title": "Pure Swift",
        "feature.pureSwift.subtitle": "No ncurses",
        "feature.declarative.title": "Declarative",
        "feature.declarative.subtitle": "SwiftUI-like",
        "feature.composable.title": "Composable",
        "feature.composable.subtitle": "View protocol",
        "feature.unicode.title": "Unicode compatible",
        "feature.sfSymbols.title": "Supports SF Symbols",
        "feature.sfSymbols.macOSOnly": "(macOS only)\n(requires the SF Symbols font)",
        "page.theme.language": "Language",
    ]

    static let de: [String: String] = [
        "app.title": "🖥️ TUIkit Beispiel-App 💫",
        "app.subtitle": "Ein SwiftUI-ähnliches Framework für Terminal-Benutzeroberflächen 😎",
        "menu.title": "Demo auswählen",
        "menu.item.textStyles": "Textstile",
        "menu.item.colors": "Farben",
        "menu.item.containers": "Container-Ansichten",
        "menu.item.overlays": "Overlays & Modale",
        "menu.item.layout": "Layout-System",
        "menu.item.buttons": "Schaltflächen & Links",
        "menu.item.toggles": "Schalter",
        "menu.item.textFields": "Textfelder",
        "menu.item.secureFields": "Sichere Felder",
        "menu.item.radioButtons": "Optionsfelder",
        "menu.item.spinners": "Spinner",
        "menu.item.lists": "Listen",
        "menu.item.tables": "Tabellen",
        "menu.item.scrollView": "Scrollansicht",
        "menu.item.sliders": "Schieberegler",
        "menu.item.steppers": "Stepper",
        "menu.item.splitView": "Geteilte Ansicht",
        "menu.item.imageFile": "Bild (Datei)",
        "menu.item.imageURL": "Bild (URL)",
        "menu.item.emoji": "Emoji & SF Symbols",
        "menu.item.picker": "Auswahl",
        "menu.item.progress": "Fortschritt & Anzeigen",
        "menu.item.mouse": "Maus",
        "menu.item.theme": "Design",
        "menu.item.emptyState": "Leerer Zustand",
        "menu.item.tabViews": "Tab-Ansichten",
        "menu.item.forms": "Formulare",
        "status.nav": "Navi",
        "status.select": "wählen",
        "status.back": "zurück",
        "status.scroll": "scrollen",
        "feature.pureSwift.title": "Reines Swift",
        "feature.pureSwift.subtitle": "Kein ncurses",
        "feature.declarative.title": "Deklarativ",
        "feature.declarative.subtitle": "SwiftUI-ähnlich",
        "feature.composable.title": "Komponierbar",
        "feature.composable.subtitle": "View-Protokoll",
        "feature.unicode.title": "Unicode-kompatibel",
        "feature.sfSymbols.title": "Unterstützt SF Symbols",
        "feature.sfSymbols.macOSOnly": "(nur macOS)\n(erfordert die SF-Symbols-Schrift)",
        "page.theme.language": "Sprache",
    ]

    static let fr: [String: String] = [
        "app.title": "🖥️ Application exemple TUIkit 💫",
        "app.subtitle": "Un framework de type SwiftUI pour les interfaces de terminal 😎",
        "menu.title": "Choisir une démo",
        "menu.item.textStyles": "Styles de texte",
        "menu.item.colors": "Couleurs",
        "menu.item.containers": "Vues conteneurs",
        "menu.item.overlays": "Superpositions et modales",
        "menu.item.layout": "Système de mise en page",
        "menu.item.buttons": "Boutons et liens",
        "menu.item.toggles": "Interrupteurs",
        "menu.item.textFields": "Champs de texte",
        "menu.item.secureFields": "Champs sécurisés",
        "menu.item.radioButtons": "Boutons radio",
        "menu.item.spinners": "Indicateurs",
        "menu.item.lists": "Listes",
        "menu.item.tables": "Tableaux",
        "menu.item.scrollView": "Vue défilante",
        "menu.item.sliders": "Curseurs",
        "menu.item.steppers": "Incrémenteurs",
        "menu.item.splitView": "Vue divisée",
        "menu.item.imageFile": "Image (fichier)",
        "menu.item.imageURL": "Image (URL)",
        "menu.item.emoji": "Émoji et SF Symbols",
        "menu.item.picker": "Sélecteur",
        "menu.item.progress": "Progression et jauges",
        "menu.item.mouse": "Souris",
        "menu.item.theme": "Thème",
        "menu.item.emptyState": "État vide",
        "menu.item.tabViews": "Vues à onglets",
        "menu.item.forms": "Formulaires",
        "status.nav": "navig.",
        "status.select": "choisir",
        "status.back": "retour",
        "status.scroll": "défiler",
        "feature.pureSwift.title": "Swift pur",
        "feature.pureSwift.subtitle": "Sans ncurses",
        "feature.declarative.title": "Déclaratif",
        "feature.declarative.subtitle": "Type SwiftUI",
        "feature.composable.title": "Composable",
        "feature.composable.subtitle": "Protocole View",
        "feature.unicode.title": "Compatible Unicode",
        "feature.sfSymbols.title": "Compatible SF Symbols",
        "feature.sfSymbols.macOSOnly": "(macOS uniquement)\n(nécessite la police SF Symbols)",
        "page.theme.language": "Langue",
    ]

    static let it: [String: String] = [
        "app.title": "🖥️ App di esempio TUIkit 💫",
        "app.subtitle": "Un framework in stile SwiftUI per interfacce da terminale 😎",
        "menu.title": "Scegli una demo",
        "menu.item.textStyles": "Stili di testo",
        "menu.item.colors": "Colori",
        "menu.item.containers": "Viste contenitore",
        "menu.item.overlays": "Overlay e modali",
        "menu.item.layout": "Sistema di layout",
        "menu.item.buttons": "Pulsanti e collegamenti",
        "menu.item.toggles": "Interruttori",
        "menu.item.textFields": "Campi di testo",
        "menu.item.secureFields": "Campi sicuri",
        "menu.item.radioButtons": "Pulsanti di opzione",
        "menu.item.spinners": "Indicatori",
        "menu.item.lists": "Elenchi",
        "menu.item.tables": "Tabelle",
        "menu.item.scrollView": "Vista a scorrimento",
        "menu.item.sliders": "Cursori",
        "menu.item.steppers": "Stepper",
        "menu.item.splitView": "Vista divisa",
        "menu.item.imageFile": "Immagine (file)",
        "menu.item.imageURL": "Immagine (URL)",
        "menu.item.emoji": "Emoji e SF Symbols",
        "menu.item.picker": "Selettore",
        "menu.item.progress": "Avanzamento e indicatori",
        "menu.item.mouse": "Mouse",
        "menu.item.theme": "Tema",
        "menu.item.emptyState": "Stato vuoto",
        "menu.item.tabViews": "Viste a schede",
        "menu.item.forms": "Moduli",
        "status.nav": "navig.",
        "status.select": "scegli",
        "status.back": "indietro",
        "status.scroll": "scorri",
        "feature.pureSwift.title": "Swift puro",
        "feature.pureSwift.subtitle": "Niente ncurses",
        "feature.declarative.title": "Dichiarativo",
        "feature.declarative.subtitle": "Stile SwiftUI",
        "feature.composable.title": "Componibile",
        "feature.composable.subtitle": "Protocollo View",
        "feature.unicode.title": "Compatibile Unicode",
        "feature.sfSymbols.title": "Supporta SF Symbols",
        "feature.sfSymbols.macOSOnly": "(solo macOS)\n(richiede il font SF Symbols)",
        "page.theme.language": "Lingua",
    ]

    static let es: [String: String] = [
        "app.title": "🖥️ App de ejemplo TUIkit 💫",
        "app.subtitle": "Un framework tipo SwiftUI para interfaces de terminal 😎",
        "menu.title": "Elige una demo",
        "menu.item.textStyles": "Estilos de texto",
        "menu.item.colors": "Colores",
        "menu.item.containers": "Vistas contenedoras",
        "menu.item.overlays": "Superposiciones y modales",
        "menu.item.layout": "Sistema de diseño",
        "menu.item.buttons": "Botones y enlaces",
        "menu.item.toggles": "Interruptores",
        "menu.item.textFields": "Campos de texto",
        "menu.item.secureFields": "Campos seguros",
        "menu.item.radioButtons": "Botones de opción",
        "menu.item.spinners": "Indicadores",
        "menu.item.lists": "Listas",
        "menu.item.tables": "Tablas",
        "menu.item.scrollView": "Vista de desplazamiento",
        "menu.item.sliders": "Controles deslizantes",
        "menu.item.steppers": "Steppers",
        "menu.item.splitView": "Vista dividida",
        "menu.item.imageFile": "Imagen (archivo)",
        "menu.item.imageURL": "Imagen (URL)",
        "menu.item.emoji": "Emoji y SF Symbols",
        "menu.item.picker": "Selector",
        "menu.item.progress": "Progreso e indicadores",
        "menu.item.mouse": "Ratón",
        "menu.item.theme": "Tema",
        "menu.item.emptyState": "Estado vacío",
        "menu.item.tabViews": "Vistas con pestañas",
        "menu.item.forms": "Formularios",
        "status.nav": "naveg.",
        "status.select": "elegir",
        "status.back": "atrás",
        "status.scroll": "desplazar",
        "feature.pureSwift.title": "Swift puro",
        "feature.pureSwift.subtitle": "Sin ncurses",
        "feature.declarative.title": "Declarativo",
        "feature.declarative.subtitle": "Estilo SwiftUI",
        "feature.composable.title": "Componible",
        "feature.composable.subtitle": "Protocolo View",
        "feature.unicode.title": "Compatible con Unicode",
        "feature.sfSymbols.title": "Compatible con SF Symbols",
        "feature.sfSymbols.macOSOnly": "(solo macOS)\n(requiere la fuente SF Symbols)",
        "page.theme.language": "Idioma",
    ]

    static let zh: [String: String] = [
        "app.title": "🖥️ TUIkit 示例应用 💫",
        "app.subtitle": "一个类似 SwiftUI 的终端用户界面框架 😎",
        "menu.title": "选择一个演示",
        "menu.item.textStyles": "文本样式",
        "menu.item.colors": "颜色",
        "menu.item.containers": "容器视图",
        "menu.item.overlays": "浮层与模态框",
        "menu.item.layout": "布局系统",
        "menu.item.buttons": "按钮与链接",
        "menu.item.toggles": "开关",
        "menu.item.textFields": "文本框",
        "menu.item.secureFields": "密码框",
        "menu.item.radioButtons": "单选按钮",
        "menu.item.spinners": "加载指示器",
        "menu.item.lists": "列表",
        "menu.item.tables": "表格",
        "menu.item.scrollView": "滚动视图",
        "menu.item.sliders": "滑块",
        "menu.item.steppers": "步进器",
        "menu.item.splitView": "分栏视图",
        "menu.item.imageFile": "图片（文件）",
        "menu.item.imageURL": "图片（URL）",
        "menu.item.emoji": "表情符号与 SF Symbols",
        "menu.item.picker": "选择器",
        "menu.item.progress": "进度与仪表",
        "menu.item.mouse": "鼠标",
        "menu.item.theme": "主题",
        "menu.item.emptyState": "空状态",
        "menu.item.tabViews": "标签页视图",
        "menu.item.forms": "表单",
        "status.nav": "导航",
        "status.select": "选择",
        "status.back": "返回",
        "status.scroll": "滚动",
        "feature.pureSwift.title": "纯 Swift",
        "feature.pureSwift.subtitle": "无需 ncurses",
        "feature.declarative.title": "声明式",
        "feature.declarative.subtitle": "类 SwiftUI",
        "feature.composable.title": "可组合",
        "feature.composable.subtitle": "View 协议",
        "feature.unicode.title": "兼容 Unicode",
        "feature.sfSymbols.title": "支持 SF Symbols",
        "feature.sfSymbols.macOSOnly": "(仅 macOS)\n(需安装 SF Symbols 字体)",
        "page.theme.language": "语言",
    ]

    static let ja: [String: String] = [
        "app.title": "🖥️ TUIkit サンプルアプリ 💫",
        "app.subtitle": "ターミナルUI向けのSwiftUIライクなフレームワーク 😎",
        "menu.title": "デモを選択",
        "menu.item.textStyles": "テキストスタイル",
        "menu.item.colors": "カラー",
        "menu.item.containers": "コンテナビュー",
        "menu.item.overlays": "オーバーレイとモーダル",
        "menu.item.layout": "レイアウトシステム",
        "menu.item.buttons": "ボタンとリンク",
        "menu.item.toggles": "トグル",
        "menu.item.textFields": "テキストフィールド",
        "menu.item.secureFields": "セキュアフィールド",
        "menu.item.radioButtons": "ラジオボタン",
        "menu.item.spinners": "スピナー",
        "menu.item.lists": "リスト",
        "menu.item.tables": "テーブル",
        "menu.item.scrollView": "スクロールビュー",
        "menu.item.sliders": "スライダー",
        "menu.item.steppers": "ステッパー",
        "menu.item.splitView": "分割ビュー",
        "menu.item.imageFile": "画像（ファイル）",
        "menu.item.imageURL": "画像（URL）",
        "menu.item.emoji": "絵文字と SF Symbols",
        "menu.item.picker": "ピッカー",
        "menu.item.progress": "進捗とゲージ",
        "menu.item.mouse": "マウス",
        "menu.item.theme": "テーマ",
        "menu.item.emptyState": "空の状態",
        "menu.item.tabViews": "タブビュー",
        "menu.item.forms": "フォーム",
        "status.nav": "移動",
        "status.select": "選択",
        "status.back": "戻る",
        "status.scroll": "スクロール",
        "feature.pureSwift.title": "純粋なSwift",
        "feature.pureSwift.subtitle": "ncurses不要",
        "feature.declarative.title": "宣言的",
        "feature.declarative.subtitle": "SwiftUIライク",
        "feature.composable.title": "コンポーザブル",
        "feature.composable.subtitle": "Viewプロトコル",
        "feature.unicode.title": "Unicode対応",
        "feature.sfSymbols.title": "SF Symbols 対応",
        "feature.sfSymbols.macOSOnly": "(macOS のみ)\n(SF Symbols フォントが必要)",
        "page.theme.language": "言語",
    ]
}
