#!/usr/bin/env python3
"""Generates Sources/TUIkitStyling/Theme/RowFillTable.swift from values.json.

The sixteen shipped palettes' row fills are constants chosen at coding time, so the framework reads
them rather than deriving them: the selected row (S), the cursor row's breath (F) and the selected
cursor row's breath (B), at truecolour and as 256-colour cube entries. values.json is the frozen
record of the design that chose them (2026-09-29); change a look there, re-run this, and commit both.

    python3 Tools/RowFillValues/generate.py            # rewrite the Swift table
    python3 Tools/RowFillValues/generate.py --check    # exit 1 if the table is stale (CI)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
TABLE = os.path.join(ROOT, 'Sources', 'TUIkitStyling', 'Theme', 'RowFillTable.swift')
ENDS = ('S', 'Fd', 'Ft', 'Bd', 'Bt')


def swift_table(palettes):
    h = lambda c: '0x' + c.lstrip('#').upper()
    lines = [
        '//  🖥️ TUIkit — Terminal UI Kit for Swift',
        '//  RowFillTable.swift',
        '//',
        '//  GENERATED by Tools/RowFillValues/generate.py from values.json -- do not edit. The row fills',
        '//  of the sixteen shipped palettes, chosen at coding time: truecolour (0xRRGGBB) and 256-colour',
        '//  entries, each as (S, F dim, F top, B dim, B top).',
        '//',
        '//  Created by Wade Tregaskis',
        '//  License: MIT',
        '',
        'extension RowFills {',
        '    static let shipped: [Entry] = [',
    ]
    for p in palettes:
        t, c = p['truecolour'], p['cube']
        lines += [
            f"        // {p['name']}",
            f"        Entry(key: ({', '.join(h(k) for k in p['key'])}),",
            f"              truecolour: ({', '.join(h(t[e]) for e in ENDS)}),",
            f"              cube: ({', '.join(str(c[e]) for e in ENDS)})),",
        ]
    return '\n'.join(lines + ['    ]', '}', ''])


def main():
    palettes = json.load(open(os.path.join(HERE, 'values.json')))['palettes']
    text = swift_table(palettes)
    if '--check' in sys.argv:
        current = open(TABLE).read() if os.path.exists(TABLE) else ''
        if current != text:
            print(f'{os.path.relpath(TABLE, ROOT)} is stale: run python3 Tools/RowFillValues/generate.py')
            return 1
        print('RowFillTable.swift is up to date')
        return 0
    open(TABLE, 'w').write(text)
    print(f'wrote {os.path.relpath(TABLE, ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
