#!/usr/bin/env python3
"""Generates Sources/TUIkitStyling/Theme/RowFillTable.swift from values.json.

The sixteen shipped palettes' row fills are constants chosen at coding time, so the framework reads
them rather than deriving them: the selected row (S), the cursor row's breath (F) and the selected
cursor row's breath (B), at truecolour and as 256-colour cube entries. values.json is the frozen
record of the design that chose them (2026-09-29); change a look there, re-run this, and commit both.

    python3 Tools/RowFillValues/generate.py            # rewrite the Swift table and the rule's goldens
    python3 Tools/RowFillValues/generate.py --check    # exit 1 if either is stale (CI)
    python3 Tools/RowFillValues/generate.py --ramps    # the 256-colour breaths' steps, for PulseRampTests

Every other palette runs a rule at runtime (RowFillRule.swift), whose reference is rule.py here. The
goldens are rule.py's answers for the palettes in runtime_palettes.json, which RowFillRuleTests holds
the Swift rule to: change the rule in both places, re-run this, and commit all three.

`cube_ramp` below is the reference for `Color.cubeRamp(from:to:)`: the steps every caller draws
between two cube entries. It uses the same colour maths as TUIkitStyling (WCAG luminance, CIE L*,
OKLab), so the two agree to the bit on the shipped breaths.
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
TABLE = os.path.join(ROOT, 'Sources', 'TUIkitStyling', 'Theme', 'RowFillTable.swift')
GOLDENS = os.path.join(ROOT, 'Tests', 'TUIkitStylingTests', 'RowFillRuleGoldens.swift')
ENDS = ('S', 'Fd', 'Ft', 'Bd', 'Bt')


def cube_rgb(index):
    """xterm's RGB for a 256-colour entry from 16 up (Color.palette256ToRGB)."""
    if index >= 232:
        grey = 8 + (index - 232) * 10
        return (grey, grey, grey)
    levels = (0, 95, 135, 175, 215, 255)
    i = index - 16
    return (levels[i // 36], levels[i % 36 // 6], levels[i % 6])


def linear(byte):
    c = byte / 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def lightness(rgb):
    """Color.perceivedLightness: CIE L* of the WCAG relative luminance."""
    y = 0.2126 * linear(rgb[0]) + 0.7152 * linear(rgb[1]) + 0.0722 * linear(rgb[2])
    return 116 * (y ** (1 / 3) if y > 0.008856 else 7.787 * y + 16 / 116) - 16


def oklab(rgb):
    r, g, b = (linear(x) for x in rgb)
    cbrt = lambda v: math.copysign(abs(v) ** (1 / 3), v)
    l_ = cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
    m_ = cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
    s_ = cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
    return (0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
            1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
            0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_)


def cube_ramp(dim, bright, family_deg=30.0):
    """The steps between two cube entries: [dim, middle, bright], or [dim, bright] where no entry fits.

    The middle is the entry nearest the ends' OKLab midpoint whose L* lies >= 2 inside both ends, within
    `family_deg` OKLCh of each end's hue (a grey between two greys); ties go to the lower index. A grey end
    and a hued one get no middle: there it would be the cube's darkest tinted entry, where S sits."""
    if dim == bright:
        return [dim]
    a, b = cube_rgb(dim), cube_rgb(bright)
    lo = min(lightness(a), lightness(b)) + 2
    hi = max(lightness(a), lightness(b)) - 2
    if hi < lo:
        return [dim, bright]
    grey = lambda c: c[0] == c[1] == c[2]
    hue = lambda lab: math.degrees(math.atan2(lab[2], lab[1]))
    gap = lambda x, y: min(abs(x - y) % 360, 360 - abs(x - y) % 360)
    oa, ob = oklab(a), oklab(b)
    ha = None if grey(a) else hue(oa)
    hb = None if grey(b) else hue(ob)
    if (ha is None) != (hb is None):
        return [dim, bright]
    mid = tuple((x + y) / 2 for x, y in zip(oa, ob))
    best = None
    for i in range(16, 256):
        e = cube_rgb(i)
        if i in (dim, bright) or not (lo <= lightness(e) <= hi) or grey(e) != (hb is None):
            continue
        oe = oklab(e)
        if hb is not None and (gap(hue(oe), hb) > family_deg or gap(hue(oe), ha) > family_deg):
            continue
        d = sum((x - y) ** 2 for x, y in zip(oe, mid))
        if best is None or d < best[0]:
            best = (d, i)
    return [dim, best[1], bright] if best else [dim, bright]


def swift_table(palettes):
    h = lambda c: '0x' + c.lstrip('#').upper()
    lines = [
        '//  🖥️ TUIkit — Terminal UI Kit for Swift',
        '//  RowFillTable.swift',
        '//',
        '//  GENERATED by Tools/RowFillValues/generate.py from values.json -- do not edit. The row fills',
        '//  of the sixteen shipped palettes, chosen at coding time: truecolour (0xRRGGBB) and 256-colour',
        '//  entries, each as (S, F dim, F top, B dim, B top).',
        '//',
        '//  Created by Wade Tregaskis',
        '//  License: MIT',
        '',
        'extension RowFills {',
        '    static let shipped: [Entry] = [',
    ]
    for p in palettes:
        t, c = p['truecolour'], p['cube']
        lines += [
            f"        // {p['name']}",
            f"        Entry(key: ({', '.join(h(k) for k in p['key'])}),",
            f"              truecolour: ({', '.join(h(t[e]) for e in ENDS)}),",
            f"              cube: ({', '.join(str(c[e]) for e in ENDS)})),",
        ]
    return '\n'.join(lines + ['    ]', '}', ''])


def swift_goldens():
    """RowFillRuleGoldens.swift: rule.py's truecolour and 256 looks for every runtime palette."""
    import rule
    palettes = json.load(open(os.path.join(HERE, 'runtime_palettes.json')))['palettes']
    hexes = lambda looks: ', '.join('0x%02X%02X%02X' % tuple(c) for c in looks)
    lines = []
    for p in palettes:
        c = {k: tuple(int(p[n][i:i + 2], 16) for i in (0, 2, 4)) for k, n in
             (('bg', 'page'), ('fg', 'text'), ('sec', 'secondary'), ('accent', 'accent'))}
        c['kind'] = 'live' if p['live'] else 'custom'
        true = rule.rule_true(c)
        cube = rule.rule_256(c, true)
        ends = lambda lk: [lk['S'], lk['F'][0], lk['F'][1], lk['B'][0], lk['B'][1]]
        indices = ', '.join(str(rule._INDEX[tuple(x)]) for x in ends(cube))
        lines.append(f"    RowFillGolden(\"{p['name']}\", page: 0x{p['page']}, text: 0x{p['text']}, "
                     f"secondary: 0x{p['secondary']}, accent: 0x{p['accent']}, live: {'true' if p['live'] else 'false'},\n"
                     f"        truecolour: ({hexes(ends(true))}), cube: ({indices})),")
    return GOLDENS_TEMPLATE.replace('COUNT', str(len(palettes))).replace('LINES', '\n'.join(lines))


GOLDENS_TEMPLATE = '''//  🖥️ TUIkit — Terminal UI Kit for Swift
//  RowFillRuleGoldens.swift
//
//  GENERATED by Tools/RowFillValues/generate.py from rule.py and runtime_palettes.json.
//  Do not edit: change the rule there, re-run the generator, and commit both.
//
//  Created by Wade Tregaskis
//  License: MIT

import Testing

/// One runtime palette and the reference rule's fills for it: (S, F dim, F top,
/// B dim, B top), as 0xRRGGBB at truecolour and as cube entries at 256 colours.
struct RowFillGolden: Sendable, CustomTestStringConvertible {
    let name: String
    let page: UInt32
    let text: UInt32
    let secondary: UInt32
    let accent: UInt32
    let live: Bool
    let truecolour: (UInt32, UInt32, UInt32, UInt32, UInt32)
    let cube: (UInt8, UInt8, UInt8, UInt8, UInt8)

    init(
        _ name: String, page: UInt32, text: UInt32, secondary: UInt32, accent: UInt32, live: Bool,
        truecolour: (UInt32, UInt32, UInt32, UInt32, UInt32), cube: (UInt8, UInt8, UInt8, UInt8, UInt8)
    ) {
        (self.name, self.page, self.text, self.secondary, self.accent) = (name, page, text, secondary, accent)
        (self.live, self.truecolour, self.cube) = (live, truecolour, cube)
    }

    var testDescription: String { name }
}

/// rule.py's answers for the COUNT palettes in runtime_palettes.json.
let rowFillRuleGoldens: [RowFillGolden] = [
LINES
]
'''


def main():
    palettes = json.load(open(os.path.join(HERE, 'values.json')))['palettes']
    if '--ramps' in sys.argv:
        for p in palettes:
            c = p['cube']
            for row in 'FB':
                d, b = c[row + 'd'], c[row + 't']
                print(f"        ({d}, {b}, {cube_ramp(d, b)}),  // {p['name']} {row}")
        return 0
    outputs = ((TABLE, swift_table(palettes)), (GOLDENS, swift_goldens()))
    if '--check' in sys.argv:
        stale = [path for path, text in outputs if (open(path).read() if os.path.exists(path) else '') != text]
        for path in stale:
            print(f'{os.path.relpath(path, ROOT)} is stale: run python3 Tools/RowFillValues/generate.py')
        if not stale:
            print('RowFillTable.swift and RowFillRuleGoldens.swift are up to date')
        return 1 if stale else 0
    for path, text in outputs:
        open(path, 'w').write(text)
        print(f'wrote {os.path.relpath(path, ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
