//  🖥️ TUIkit — Terminal UI Kit for Swift
//  RowFills.swift
//
//  What a list or table row's highlight paints: the shipped palettes' fills,
//  chosen at coding time, and every other palette's, from the rule.
//
//  Created by Wade Tregaskis
//  License: MIT

import Foundation

/// The fills of a palette's highlighted rows at one colour depth.
///
/// Two backgrounds stand still: a plain row sits on the page, a selected row on
/// ``selection`` (S). Focus — the cursor — extends whichever it is on. The
/// unselected cursor row breathes from ``focusDim``, a little above the page, to
/// ``focusBright`` (F); the selected cursor row from ``emphasisDim``, a little
/// above S, to ``emphasisBright`` (B). The dim ends only need to stay
/// distinguishable from what they extend; the top ends are what call the cursor
/// out, and B's peaks above F's and S, so a row that is both reads as both.
///
/// The sixteen shipped palettes' fills are constants (`RowFillTable.swift`,
/// generated by `Tools/RowFillValues/generate.py`), because a palette whose
/// colours are known at coding time needs no rule run at render time. Every other
/// palette — a custom one, the terminal's own colours, a `.tint` subtree — runs
/// ``RowFillRule`` once per depth, and keeps the answer.
///
/// A colour a palette states is used as it is stated. The one row fill a palette
/// can state is its cursor row's wash, ``Palette/focusBackground``: where it states
/// one, that is F's dim end at truecolour, with F's top twice as far from the page
/// (``Palette/focusWashPulse()``), and the rule places only what derives from the
/// accent — S and B. On a 256-colour terminal the stated wash's cube entries are
/// kept where they still hold the rule's invariants beside S and B, and moved
/// where they do not: nobody chooses colours for a cube they may never see. A
/// shipped palette's own wash, carried through a `.tint`, was chosen for the
/// shipped accent and not for this one, so there the rule places F too.
///
/// On a 16-colour terminal the fills are slots of the table the terminal reports
/// (xterm's until it reports one). The shipped palettes carry their picks for
/// xterm's and Apple Terminal's default tables; any other table, and every other
/// palette, runs the rule against it. Sixteen colours are sometimes too few to keep
/// every state apart, and then one end of a breath is reverse video
/// (``reversedFocusEnd``, ``reversedEmphasisEnd``).
///
/// `nil` without colour, and where a colour cannot be measured (the terminal's own
/// before it has reported it): the callers keep their own rule there.
package struct RowFills: Equatable, Sendable {
    /// S: a selected row away from the cursor.
    package let selection: Color
    /// F's dim end: the unselected cursor row's breath, a little above the page.
    package let focusDim: Color
    /// F's top end.
    package let focusBright: Color
    /// B's dim end: the selected cursor row's breath, a little above S.
    package let emphasisDim: Color
    /// B's top end, the brightest of the five.
    package let emphasisBright: Color
    /// Which end of F is reverse video — 16 colours only. That end's colour above is
    /// the other end's, so a site that cannot draw a reversal holds a legible fill.
    package var reversedFocusEnd: BreathEnd?
    /// Which end of B is reverse video, as ``reversedFocusEnd``.
    package var reversedEmphasisEnd: BreathEnd?

    /// One end of a breath.
    package enum BreathEnd: Sendable {
        case dim
        case top
    }
}

extension RowFills {
    /// One shipped palette's fills, as `Tools/RowFillValues/generate.py` writes them.
    struct Entry: Sendable {
        /// The page, text, secondary text and accent the fills were chosen for,
        /// as 0xRRGGBB with any alpha spent over the page.
        let key: (UInt32, UInt32, UInt32, UInt32)
        /// (S, F dim, F top, B dim, B top) at truecolour, as 0xRRGGBB.
        let truecolour: (UInt32, UInt32, UInt32, UInt32, UInt32)
        /// The same at 256 colours, as cube entries.
        let cube: (UInt8, UInt8, UInt8, UInt8, UInt8)
        /// The same at 16 colours, as slots of xterm's and of Apple Terminal's default
        /// tables, -1 for reverse video.
        let sixteen: (xterm: RowFills.Picks, apple: RowFills.Picks)
    }

    /// The shipped entry chosen for these four colours, or `nil`.
    ///
    /// Keyed by the colours the fills depend on, not by palette identity: a
    /// customised copy of a shipped palette keeps its source's `id` but not
    /// necessarily its colours. Each channel may be up to 2 off, so a colour
    /// that took a slightly different route to the same shade still matches;
    /// no two shipped keys are that close, so no palette can match the wrong
    /// one.
    static func entry(page: UInt32, text: UInt32, secondary: UInt32, accent: UInt32) -> Entry? {
        func near(_ first: UInt32, _ second: UInt32) -> Bool {
            for shift: UInt32 in [0, 8, 16] {
                let one = Int((first >> shift) & 0xFF)
                let two = Int((second >> shift) & 0xFF)
                if abs(one - two) > 2 { return false }
            }
            return true
        }
        return shipped.first { entry in
            near(entry.key.0, page) && near(entry.key.1, text) && near(entry.key.2, secondary)
                && near(entry.key.3, accent)
        }
    }
}

extension RowFills.Entry {
    /// This entry's fills at `depth` (256 colours or truecolour).
    func fills(at depth: ColorDepth) -> RowFills {
        if depth == .palette256 {
            let (selection, focusDim, focusBright, emphasisDim, emphasisBright) = cube
            return RowFills(
                selection: .palette256(selection), focusDim: .palette256(focusDim),
                focusBright: .palette256(focusBright), emphasisDim: .palette256(emphasisDim),
                emphasisBright: .palette256(emphasisBright))
        }
        func colour(_ packed: UInt32) -> Color {
            .rgb(UInt8(packed >> 16 & 0xFF), UInt8(packed >> 8 & 0xFF), UInt8(packed & 0xFF))
        }
        let (selection, focusDim, focusBright, emphasisDim, emphasisBright) = truecolour
        return RowFills(
            selection: colour(selection), focusDim: colour(focusDim), focusBright: colour(focusBright),
            emphasisDim: colour(emphasisDim), emphasisBright: colour(emphasisBright))
    }
}

// MARK: - Runtime palettes

extension RowFills {
    /// What a runtime palette's fills depend on.
    struct RuleKey: Hashable {
        let page: UInt32
        let text: UInt32
        let secondary: UInt32
        let accent: UInt32
        /// The page and the text are the terminal's own, drawn as SGR 49 and 39.
        let live: Bool
        let depth: ColorDepth
        /// F where the palette states its wash, at truecolour.
        let statedWash: [Color]?
        /// At 16 colours: the slots the terminal paints, 0xRRGGBB.
        var table: [UInt32]?
        /// At 16 colours, for a shipped palette on a table it has no picks for: its
        /// truecolour fills, which the slots are placed toward.
        var shippedTarget: [UInt32]?
    }

    private static let cacheLock = NSLock()
    nonisolated(unsafe) private static var cache: [RuleKey: RowFills] = [:]

    /// The rule's fills for `key`, run once and kept.
    static func ruled(_ key: RuleKey) -> RowFills {
        if let known = cacheLock.withLock({ cache[key] }) { return known }
        let answer = run(key)
        cacheLock.withLock {
            // A backstop against unbounded growth, as `Color.pulseRamp`'s cache has: an
            // app has a handful of palettes and tints at one depth.
            if cache.count > 64 { cache.removeAll(keepingCapacity: true) }
            cache[key] = answer
        }
        return answer
    }

    private static func run(_ key: RuleKey) -> RowFills {
        func colour(_ packed: UInt32) -> Color {
            .rgb(UInt8(packed >> 16 & 0xFF), UInt8(packed >> 8 & 0xFF), UInt8(packed & 0xFF))
        }
        let rule = RowFillRule(
            page: colour(key.page), text: colour(key.text), secondary: colour(key.secondary),
            accent: colour(key.accent), live: key.live)
        let look = rule.truecolour()
        if key.depth < .palette256 { return sixteen(key, rule: rule, look: look) }
        guard key.depth == .palette256 else {
            return RowFills(
                selection: look.selection.color, focusDim: key.statedWash?[0] ?? look.focus.dim.color,
                focusBright: key.statedWash?[1] ?? look.focus.top.color, emphasisDim: look.emphasis.dim.color,
                emphasisBright: look.emphasis.top.color)
        }
        var cube = rule.cube(toward: look)
        if let wash = key.statedWash {
            if let (dimRed, dimGreen, dimBlue) = wash[0].rgbComponents,
                let (topRed, topGreen, topBlue) = wash[1].rgbComponents
            {
                let stated = (
                    RowFillRule.at256(rule.swatch(dimRed, dimGreen, dimBlue)),
                    RowFillRule.at256(rule.swatch(topRed, topGreen, topBlue)))
                if rule.holds256(cube.selection, stated, cube.emphasis) { cube.focus = stated }
            } else {
                // A wash with no RGB is drawn as it is stated: there is nothing to check.
                return RowFills(
                    selection: entry(cube.selection), focusDim: wash[0], focusBright: wash[1],
                    emphasisDim: entry(cube.emphasis.dim), emphasisBright: entry(cube.emphasis.top))
            }
        }
        return RowFills(
            selection: entry(cube.selection), focusDim: entry(cube.focus.dim), focusBright: entry(cube.focus.top),
            emphasisDim: entry(cube.emphasis.dim), emphasisBright: entry(cube.emphasis.top))
    }

    /// A cube swatch as the `.palette256` entry it is.
    static func entry(_ swatch: RowFillRule.Swatch) -> Color {
        RowFillRule.cubeIndex[swatch.packed].map(Color.palette256) ?? swatch.color
    }

    /// Each shipped palette's page and wash, to tell a shipped palette's own wash,
    /// carried through a `.tint`, from one a customiser stated.
    static let shippedWashes: [(page: Color, wash: Color)] =
        (PaletteRegistry.phosphorPresets + PaletteRegistry.appleTerminalProfiles).map {
            ($0.background, $0.focusBackground)
        }
}

extension Palette {
    /// This palette's row fills at `depth`, or `nil` where it has none — see
    /// ``RowFills``.
    ///
    /// - Parameter surface: What the rows sit on, when that is not the page: the rule
    ///   places the fills with it as their page. Only B is asked for there
    ///   (``Palette/accentFillPulse(over:)``), so a stated wash plays no part.
    package func rowFills(at depth: ColorDepth = .current, over surface: Color? = nil) -> RowFills? {
        guard depth > .noColor else { return nil }
        let page = surface ?? background
        func packed(_ colour: Color) -> UInt32? {
            guard let (red, green, blue) = colour.spendingAlpha(over: page).rgbComponents else { return nil }
            return UInt32(red) << 16 | UInt32(green) << 8 | UInt32(blue)
        }
        guard let pageRGB = packed(page), let textRGB = packed(foreground),
            let secondaryRGB = packed(foregroundSecondary), let accentRGB = packed(accent)
        else { return nil }
        let entry = RowFills.entry(page: pageRGB, text: textRGB, secondary: secondaryRGB, accent: accentRGB)
        let table = depth < .palette256 ? RowFills.reportedTable() : nil
        if let entry {
            if let table {
                if let fills = entry.fills(on: table) { return fills }
            } else {
                return entry.fills(at: depth)
            }
        }
        func isTerminals(_ colour: Color) -> Bool {
            switch colour.value {
            case .terminalBackground, .terminalForeground, .terminalDefault: true
            default: false
            }
        }
        let wash = (surface == nil ? statedFocusWash() : nil).map { wash in
            let (dim, bright) = washPulse(wash)
            return [dim, bright]
        }
        return RowFills.ruled(
            RowFills.RuleKey(
                page: pageRGB, text: textRGB, secondary: secondaryRGB, accent: accentRGB,
                live: isTerminals(page) || isTerminals(foreground), depth: depth,
                statedWash: entry == nil ? wash : nil, table: table,
                shippedTarget: entry.map { entry in
                    let (selection, focusDim, focusTop, emphasisDim, emphasisTop) = entry.truecolour
                    return [selection, focusDim, focusTop, emphasisDim, emphasisTop]
                }))
    }

    /// ``focusBackground`` where this palette states its own, or `nil` where it is
    /// the derived default, or a shipped palette's own (reached through a `.tint`,
    /// which forwards it with a different accent).
    func statedFocusWash() -> Color? {
        let wash = focusBackground
        guard wash != derivedFocusBackground() else { return nil }
        let page = background
        if RowFills.shippedWashes.contains(where: { $0.page == page && $0.wash == wash }) { return nil }
        return wash
    }
}
