//  🖥️ TUIkit — Terminal UI Kit for Swift
//  RowFills.swift
//
//  What a list or table row's highlight paints, for the palettes whose fills were
//  chosen at coding time.
//
//  Created by Wade Tregaskis
//  License: MIT

/// The fills of a palette's highlighted rows at one colour depth.
///
/// Two backgrounds stand still: a plain row sits on the page, a selected row on
/// ``selection`` (S). Focus — the cursor — extends whichever it is on. The
/// unselected cursor row breathes from ``focusDim``, a little above the page, to
/// ``focusBright`` (F); the selected cursor row from ``emphasisDim``, a little
/// above S, to ``emphasisBright`` (B). The dim ends only need to stay
/// distinguishable from what they extend; the top ends are what call the cursor
/// out, and B's peaks above F's and S, so a row that is both reads as both.
///
/// Only the shipped palettes have fills here, and only at 256 colours and
/// truecolour: they are constants (`RowFillTable.swift`, generated by
/// `Tools/RowFillValues/generate.py`), because a palette whose colours are known
/// at coding time needs no rule run at render time. Everything else — a custom
/// palette, the terminal's own colours, a `.tint` subtree, 16 colours — gets
/// `nil`, and its caller keeps its own rule.
package struct RowFills: Equatable, Sendable {
    /// S: a selected row away from the cursor.
    package let selection: Color
    /// F's dim end: the unselected cursor row's breath, a little above the page.
    package let focusDim: Color
    /// F's top end.
    package let focusBright: Color
    /// B's dim end: the selected cursor row's breath, a little above S.
    package let emphasisDim: Color
    /// B's top end, the brightest of the five.
    package let emphasisBright: Color
}

extension RowFills {
    /// One shipped palette's fills, as `Tools/RowFillValues/generate.py` writes them.
    struct Entry: Sendable {
        /// The page, text, secondary text and accent the fills were chosen for,
        /// as 0xRRGGBB with any alpha spent over the page.
        let key: (UInt32, UInt32, UInt32, UInt32)
        /// (S, F dim, F top, B dim, B top) at truecolour, as 0xRRGGBB.
        let truecolour: (UInt32, UInt32, UInt32, UInt32, UInt32)
        /// The same at 256 colours, as cube entries.
        let cube: (UInt8, UInt8, UInt8, UInt8, UInt8)
    }

    /// The shipped entry chosen for these four colours, or `nil`.
    ///
    /// Keyed by the colours the fills depend on, not by palette identity: a
    /// customised copy of a shipped palette keeps its source's `id` but not
    /// necessarily its colours. Each channel may be up to 2 off, so a colour
    /// that took a slightly different route to the same shade still matches;
    /// no two shipped keys are that close, so no palette can match the wrong
    /// one.
    static func entry(page: UInt32, text: UInt32, secondary: UInt32, accent: UInt32) -> Entry? {
        func near(_ first: UInt32, _ second: UInt32) -> Bool {
            stride(from: 0, through: 16, by: 8).allSatisfy { shift in
                abs(Int((first >> UInt32(shift)) & 0xFF) - Int((second >> UInt32(shift)) & 0xFF)) <= 2
            }
        }
        return shipped.first { entry in
            near(entry.key.0, page) && near(entry.key.1, text) && near(entry.key.2, secondary)
                && near(entry.key.3, accent)
        }
    }
}

extension Palette {
    /// This palette's row fills at `depth`, or `nil` where it has none — see
    /// ``RowFills``.
    package func rowFills(at depth: ColorDepth = .current) -> RowFills? {
        guard depth >= .palette256 else { return nil }
        let page = background
        func packed(_ colour: Color) -> UInt32? {
            guard let (red, green, blue) = colour.spendingAlpha(over: page).rgbComponents else { return nil }
            return UInt32(red) << 16 | UInt32(green) << 8 | UInt32(blue)
        }
        guard let pageRGB = packed(page), let textRGB = packed(foreground),
            let secondaryRGB = packed(foregroundSecondary), let accentRGB = packed(accent),
            let entry = RowFills.entry(page: pageRGB, text: textRGB, secondary: secondaryRGB, accent: accentRGB)
        else { return nil }

        if depth == .palette256 {
            let (selection, focusDim, focusBright, emphasisDim, emphasisBright) = entry.cube
            return RowFills(
                selection: .palette256(selection), focusDim: .palette256(focusDim),
                focusBright: .palette256(focusBright), emphasisDim: .palette256(emphasisDim),
                emphasisBright: .palette256(emphasisBright))
        }
        func colour(_ packed: UInt32) -> Color {
            .rgb(UInt8(packed >> 16 & 0xFF), UInt8(packed >> 8 & 0xFF), UInt8(packed & 0xFF))
        }
        let (selection, focusDim, focusBright, emphasisDim, emphasisBright) = entry.truecolour
        return RowFills(
            selection: colour(selection), focusDim: colour(focusDim), focusBright: colour(focusBright),
            emphasisDim: colour(emphasisDim), emphasisBright: colour(emphasisBright))
    }
}
