//  🖥️ TUIkit — Terminal UI Kit for Swift
//  RowFillTable.swift
//
//  GENERATED by Tools/RowFillValues/generate.py from values.json -- do not edit. The row fills
//  of the sixteen shipped palettes, chosen at coding time: truecolour (0xRRGGBB), 256-colour
//  entries, and 16-colour slots for xterm's and Apple Terminal's default tables (-1 is reverse
//  video), each as (S, F dim, F top, B dim, B top).
//
//  Created by Wade Tregaskis
//  License: MIT

extension RowFills {
    static let shipped: [Entry] = [
        // Green
        Entry(key: (0x050A05, 0x33FF33, 0x27C427, 0x66FF66),
              truecolour: (0x1D471D, 0x0B300B, 0x166F16, 0x225422, 0x378937),
              cube: (22, 236, 28, 28, 70),
              sixteen: (xterm: (4, 1, 8, 9, 12), apple: (4, 1, 8, 9, 5))),
        // Amber
        Entry(key: (0x0A0805, 0xFFAA00, 0xCC8800, 0xFFCC33),
              truecolour: (0x473911, 0x352401, 0x704A00, 0x564513, 0x856A1C),
              cube: (58, 236, 94, 94, 101),
              sixteen: (xterm: (1, 4, 9, 5, 8), apple: (1, 4, 9, 8, 5))),
        // Red
        Entry(key: (0x0A0505, 0xFF4242, 0xCC3333, 0xFF6666),
              truecolour: (0x421B1B, 0x2A0B0B, 0x6F1919, 0x542222, 0x893737),
              cube: (52, 234, 88, 236, 124),
              sixteen: (xterm: (10, 4, 3, 6, 11), apple: (10, 4, 7, 14, 11))),
        // Violet
        Entry(key: (0x08050A, 0xB275F0, 0x8C3CDD, 0xC797F7),
              truecolour: (0x342741, 0x2B1144, 0x56208B, 0x413151, 0x624A79),
              cube: (53, 234, 90, 54, 92),
              sixteen: (xterm: (10, 2, 7, 3, 6), apple: (1, 4, -1, 13, 4))),
        // Blue
        Entry(key: (0x05080A, 0x00AAFF, 0x0088CC, 0x33BBFF),
              truecolour: (0x113547, 0x022131, 0x00507A, 0x144158, 0x1E6A91),
              cube: (19, 17, 20, 20, 26),
              sixteen: (xterm: (5, 1, 4, 8, 12), apple: (4, 1, 12, 8, 5))),
        // White
        Entry(key: (0x06070A, 0xE8E8E8, 0xB0B0B0, 0xFFFFFF),
              truecolour: (0x444547, 0x2C2C2C, 0x605F5C, 0x515154, 0x838385),
              cube: (238, 235, 240, 240, 244),
              sixteen: (xterm: (1, 4, -1, 13, 4), apple: (2, 1, 3, 8, 6))),
        // Basic
        Entry(key: (0xFFFFFF, 0x000000, 0x404040, 0x3E95FF),
              truecolour: (0xC9E1FF, 0xE3F0FF, 0x499BFF, 0xB4D6FF, 0x3580DB),
              cube: (117, 254, 75, 110, 32),
              sixteen: (xterm: (3, 7, 6, 14, 4), apple: (13, 11, 6, 7, 14))),
        // Grass
        Entry(key: (0x13773D, 0xFFF0A5, 0xC4D28B, 0xFFB03B),
              truecolour: (0x55873C, 0x39803D, 0x9C983C, 0x688C3C, 0xC4A23C),
              cube: (36, 101, 143, 64, 178),
              sixteen: (xterm: (12, 0, 1, 8, 9), apple: (6, 0, 1, 8, 3))),
        // Homebrew
        Entry(key: (0x000000, 0x28FE14, 0x1EBF0F, 0x00F900),
              truecolour: (0x003900, 0x000C00, 0x005000, 0x004600, 0x007D00),
              cube: (22, 234, 28, 28, 70),
              sixteen: (xterm: (1, 9, 12, 4, 8), apple: (4, 1, 5, 12, 8))),
        // Man Page
        Entry(key: (0xFEF49C, 0x000000, 0x403D27, 0x948C44),
              truecolour: (0xD0C776, 0xE2DA8B, 0x8D8856, 0xBFB768, 0x797338),
              cube: (186, 192, 144, 143, 101),
              sixteen: (xterm: (11, 15, 8, 3, 1), apple: (11, 7, 2, 3, 1))),
        // Novel
        Entry(key: (0xDFDBC3, 0x4D2F2D, 0x725A53, 0x933A21),
              truecolour: (0xCEB69E, 0xD7CBB3, 0xC19B82, 0xC7A991, 0xB17A62),
              cube: (180, 217, 202, 209, 166),
              sixteen: (xterm: (6, 15, 3, 11, 2), apple: (14, 7, 10, 11, 4))),
        // Ocean
        Entry(key: (0x2B66C9, 0xFFFFFF, 0xCAD9F2, 0x99C5FF),
              truecolour: (0x4E84DA, 0x2A73DF, 0x27A0FF, 0x5D91E1, 0x84B3F5),
              cube: (68, 27, 105, 69, 146),
              sixteen: (xterm: (5, 4, 2, 8, 13), apple: (4, 5, 12, 8, 13))),
        // Pro
        Entry(key: (0x000000, 0xF4F4F4, 0xB7B7B7, 0xFFFFFF),
              truecolour: (0x404040, 0x282828, 0x7A7A7A, 0x4D4D4D, 0x949494),
              cube: (238, 235, 243, 240, 246),
              sixteen: (xterm: (1, 2, 5, 8, 12), apple: (2, 1, 8, 3, 6))),
        // Red Sands
        Entry(key: (0x8E3527, 0xD7C9A7, 0xC5A487, 0xE6C72B),
              truecolour: (0xA25728, 0x964227, 0xB37229, 0xA86128, 0xC08829),
              cube: (95, 94, 101, 130, 172),
              sixteen: (xterm: (0, 4, -1, -1, 4), apple: (5, 0, 13, 9, 8))),
        // Silver Aerogel
        Entry(key: (0x929292, 0x000000, 0x252525, 0x43445C),
              truecolour: (0x787880, 0x808199, 0x606170, 0x6E6E79, 0x4C4D62),
              cube: (243, 103, 61, 61, 55),
              sixteen: (xterm: (12, 7, 6, 5, 4), apple: (3, 7, 6, 5, 1))),
        // Solid Colors
        Entry(key: (0xF2DEC9, 0x000000, 0x3D3832, 0x067CFF),
              truecolour: (0xBCC7D5, 0xB3D7FF, 0x85B1E2, 0xAEC2D9, 0x4395F1),
              cube: (81, 153, 75, 110, 32),
              sixteen: (xterm: (15, 14, 12, 8, 6), apple: (11, 7, 6, 13, 14))),
    ]
}
